#!/usr/bin/env python3
"""Finalize PR 125 by moving approval-phrase policy ownership into Rust."""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
COMMANDS = ROOT / "src-tauri/src/commands.rs"
CONTRACT_TEST = ROOT / "src-tauri/tests/cloud_transfer_coverage_contract.rs"
API = ROOT / "src/lib/api.ts"
API_TEST = ROOT / "src/lib/api.test.ts"
ARCHIVE = ROOT / "src/lib/CloudArchive.svelte"
CHANGELOG = ROOT / "CHANGELOG.md"
WORKFLOW = ROOT / ".github/workflows/finalize-pr125-backend-phrases.yml"
SCRIPT = Path(__file__).resolve()

TEST_NAME = "cloud_copy_approval_phrases_are_backend_owned"
TEST_SOURCE = r'''

/// Verifies that exact approval phrases are generated by Rust and only selected by TypeScript.
#[test]
fn cloud_copy_approval_phrases_are_backend_owned() {
    let commands = include_str!("../src/commands.rs");
    let api = include_str!("../../src/lib/api.ts");
    let archive = include_str!("../../src/lib/CloudArchive.svelte");

    assert!(
        commands.contains("pub struct CloudPlanOutput"),
        "the Tauri plan command must expose a documented backend-owned phrase envelope"
    );
    assert!(
        commands.contains("cloud_transfer::cloud_copy_approval_phrase("),
        "the plan response must obtain phrases from the production Rust approval function"
    );
    assert!(
        !api.contains("`DiskSage cloud ${action} ${candidate.review_fingerprint} 승인`"),
        "TypeScript must not duplicate the security-sensitive approval format"
    );
    assert!(
        api.contains("phraseSets[candidate.review_fingerprint]"),
        "TypeScript must select the backend-returned phrase by exact review fingerprint"
    );
    assert!(
        archive.contains("report?.copy_approval_phrases ?? {}"),
        "the UI must read phrases from the exact current plan response"
    );
    assert!(
        archive.contains("{@const copyOnlyApprovalPhrase"),
        "the copy-only phrase must be calculated once per rendered candidate"
    );
    assert!(
        archive.contains("{@const adoptExistingApprovalPhrase"),
        "the adoption phrase must be calculated once per rendered candidate"
    );
}
'''


def replace_once(path: Path, old: str, new: str) -> None:
    """Replace exactly one audited UTF-8 source fragment or stop without writing."""
    text = path.read_text(encoding="utf-8")
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"expected one anchor in {path}, found {count}: {old[:120]!r}")
    path.write_text(text.replace(old, new, 1), encoding="utf-8")


def add_test() -> None:
    """Append the ownership regression before production sources are changed."""
    text = CONTRACT_TEST.read_text(encoding="utf-8")
    if TEST_NAME in text:
        raise SystemExit("backend ownership regression already exists")
    CONTRACT_TEST.write_text(text.rstrip() + TEST_SOURCE + "\n", encoding="utf-8")


def apply_commands_repair() -> None:
    """Return exact Rust-generated phrases with every read-only cloud plan."""
    old = '''/// Read-only cloud offload plan. The selected destination must be one of the roots discovered
/// on this machine; this command never creates a folder or moves a file.
#[cfg(not(coverage))]
#[tauri::command(async)]
pub async fn plan_cloud_archive(
    root: String,
    cloud_root: String,
    min_size_mib: u64,
    min_age_days: u64,
    limit: usize,
    app: AppHandle,
) -> Result<cloud::CloudPlanReport, String> {
    tauri::async_runtime::spawn_blocking(move || {
        let (_, report) =
            cloud_plan_for_inputs(&root, &cloud_root, min_size_mib, min_age_days, limit, &app)?;
        Ok(report)
    })
    .await
    .map_err(|_| "cloud-plan-task-failed".to_string())?
}
'''
    new = '''/// Exact approval phrases generated by the Rust authorization policy for one review snapshot.
#[cfg(not(coverage))]
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize)]
pub struct CloudCopyApprovalPhraseSet {
    /// Exact phrase required to create a new verified cloud copy.
    pub copy_only: String,
    /// Exact phrase required to adopt an already-existing verified destination copy.
    pub adopt_existing_copy: String,
}

/// Read-only cloud plan plus approval phrases keyed by immutable review fingerprint.
#[cfg(not(coverage))]
#[derive(Debug, Clone, serde::Serialize)]
pub struct CloudPlanOutput {
    /// Existing plan fields remain flattened to preserve the established wire shape.
    #[serde(flatten)]
    pub report: cloud::CloudPlanReport,
    /// Backend-owned phrases that the UI may display but must never reconstruct.
    pub copy_approval_phrases:
        std::collections::BTreeMap<String, CloudCopyApprovalPhraseSet>,
}

/// Attach both supported action phrases to every candidate in one immutable plan response.
#[cfg(not(coverage))]
fn cloud_plan_output(report: cloud::CloudPlanReport) -> CloudPlanOutput {
    let copy_approval_phrases = report
        .candidates
        .iter()
        .map(|candidate| {
            (
                candidate.review_fingerprint.clone(),
                CloudCopyApprovalPhraseSet {
                    copy_only: cloud_transfer::cloud_copy_approval_phrase(
                        candidate,
                        cloud_transfer::CloudCopyApprovalAction::CopyOnly,
                    ),
                    adopt_existing_copy: cloud_transfer::cloud_copy_approval_phrase(
                        candidate,
                        cloud_transfer::CloudCopyApprovalAction::AdoptExistingCopy,
                    ),
                },
            )
        })
        .collect();
    CloudPlanOutput {
        report,
        copy_approval_phrases,
    }
}

/// Read-only cloud offload plan. The selected destination must be one of the roots discovered
/// on this machine; this command never creates a folder or moves a file.
#[cfg(not(coverage))]
#[tauri::command(async)]
pub async fn plan_cloud_archive(
    root: String,
    cloud_root: String,
    min_size_mib: u64,
    min_age_days: u64,
    limit: usize,
    app: AppHandle,
) -> Result<CloudPlanOutput, String> {
    tauri::async_runtime::spawn_blocking(move || {
        let (_, report) =
            cloud_plan_for_inputs(&root, &cloud_root, min_size_mib, min_age_days, limit, &app)?;
        Ok(cloud_plan_output(report))
    })
    .await
    .map_err(|_| "cloud-plan-task-failed".to_string())?
}

#[cfg(all(test, not(coverage)))]
mod cloud_plan_output_tests {
    use super::*;

    fn candidate() -> cloud::CloudCandidate {
        cloud::CloudCandidate {
            metadata_fingerprint: "a".repeat(64),
            review_fingerprint: "b".repeat(64),
            src: "/source/archive.wav".into(),
            dst: "/cloud/archive.wav".into(),
            provider: cloud::CloudProvider::Icloud,
            destination_account_scope: cloud::CloudAccountScope::Personal,
            kind: cloud::ArchiveKind::Media,
            bytes: 1024,
            age_days: 90,
            created_ms: 1,
            modified_ms: 2,
            production_time_ms: 1,
            production_time_source: "filesystem-created".into(),
            production_time_confidence: "low".into(),
            source_root: "/source".into(),
            relative_path: "archive.wav".into(),
            source_context: "source".into(),
            requires_review: false,
            review_reasons: Vec::new(),
            content_title: None,
            content_authors: Vec::new(),
            content_context: Vec::new(),
            duration_ms: None,
            dataset_profile: None,
            metadata_evidence: Vec::new(),
            blocked_reason: None,
        }
    }

    #[test]
    fn plan_output_returns_backend_phrases_for_both_copy_actions() {
        let candidate = candidate();
        let report = cloud::CloudPlanReport {
            cloud_root: cloud::CloudRoot {
                id: "icloud-personal".into(),
                provider: cloud::CloudProvider::Icloud,
                account_scope: cloud::CloudAccountScope::Personal,
                label: "iCloud Drive".into(),
                path: "/cloud".into(),
                readable: true,
                access_issue: None,
            },
            generated_at_ms: 3,
            source_selection_policy: None,
            candidates: vec![candidate.clone()],
            candidate_bytes: candidate.bytes,
            potentially_reclaimable_bytes: candidate.bytes,
            exact_duplicates: cloud::ExactDuplicateSummary::default(),
            capacity: None,
            notices: Vec::new(),
        };

        let output = cloud_plan_output(report);
        let phrases = output
            .copy_approval_phrases
            .get(&candidate.review_fingerprint)
            .expect("current candidate phrase set");
        assert_eq!(
            phrases.copy_only,
            cloud_transfer::cloud_copy_approval_phrase(
                &candidate,
                cloud_transfer::CloudCopyApprovalAction::CopyOnly,
            )
        );
        assert_eq!(
            phrases.adopt_existing_copy,
            cloud_transfer::cloud_copy_approval_phrase(
                &candidate,
                cloud_transfer::CloudCopyApprovalAction::AdoptExistingCopy,
            )
        );
    }
}
'''
    replace_once(COMMANDS, old, new)


def apply_api_repair() -> None:
    """Make TypeScript select backend phrases and fail closed when they are absent."""
    replace_once(
        API,
        '''export type CloudCopyApprovalAction = "copy-only" | "adopt-existing-copy";

export interface CloudCopyApproval {
''',
        '''export type CloudCopyApprovalAction = "copy-only" | "adopt-existing-copy";

/** Exact phrases generated by Rust for one immutable review fingerprint. */
export interface CloudCopyApprovalPhraseSet {
  /** Phrase required before a new verified cloud copy may start. */
  copy_only: string;
  /** Phrase required before an existing verified destination may be adopted. */
  adopt_existing_copy: string;
}

export interface CloudCopyApproval {
''',
    )
    replace_once(
        API,
        '''export interface CloudPlanReport {
  cloud_root: CloudRoot;
  generated_at_ms: number;
  candidates: CloudCandidate[];
''',
        '''export interface CloudPlanReport {
  cloud_root: CloudRoot;
  generated_at_ms: number;
  /** Rust-owned approval phrases keyed by the candidate's exact review fingerprint. */
  copy_approval_phrases: Readonly<Record<string, CloudCopyApprovalPhraseSet>>;
  candidates: CloudCandidate[];
''',
    )
    replace_once(
        API,
        '''export const cloudCopyApprovalPhrase = (
  candidate: Pick<CloudCandidate, "review_fingerprint">,
  action: CloudCopyApprovalAction,
) => `DiskSage cloud ${action} ${candidate.review_fingerprint} 승인`;
''',
        '''/** Select an exact Rust-generated approval phrase without reconstructing policy in UI code. */
export function cloudCopyApprovalPhrase(
  candidate: Pick<CloudCandidate, "review_fingerprint">,
  action: CloudCopyApprovalAction,
  phraseSets: Readonly<Record<string, CloudCopyApprovalPhraseSet>>,
): string | null {
  const phrases = phraseSets[candidate.review_fingerprint];
  if (!phrases) return null;
  return action === "copy-only" ? phrases.copy_only : phrases.adopt_existing_copy;
}
''',
    )


def apply_archive_repair() -> None:
    """Read exact current-plan phrases once and keep every missing-phrase path fail closed."""
    replace_once(
        ARCHIVE,
        '''  function reviewDecision(candidate: api.CloudCandidate): api.CloudReviewDecision | null {
''',
        '''  function copyApprovalPhrase(
    candidate: api.CloudCandidate,
    action: api.CloudCopyApprovalAction,
  ): string | null {
    return api.cloudCopyApprovalPhrase(
      candidate,
      action,
      report?.copy_approval_phrases ?? {},
    );
  }

  function reviewDecision(candidate: api.CloudCandidate): api.CloudReviewDecision | null {
''',
    )
    replace_once(
        ARCHIVE,
        '''    if (exactConfirmationPhrase !== api.cloudCopyApprovalPhrase(candidate, "copy-only")
      || !approvalRationale) return;
''',
        '''    const expectedPhrase = copyApprovalPhrase(candidate, "copy-only");
    if (!expectedPhrase || exactConfirmationPhrase !== expectedPhrase || !approvalRationale) return;
''',
    )
    replace_once(
        ARCHIVE,
        '''    if (exactConfirmationPhrase
        !== api.cloudCopyApprovalPhrase(candidate, "adopt-existing-copy")
      || !approvalRationale) return;
''',
        '''    const expectedPhrase = copyApprovalPhrase(candidate, "adopt-existing-copy");
    if (!expectedPhrase || exactConfirmationPhrase !== expectedPhrase || !approvalRationale) return;
''',
    )
    replace_once(
        ARCHIVE,
        '''            {#if copyEligible(candidate)}
              <div class="copy-approval">
                <div class="context">현재 메타데이터·출발지·목적지에 결부된 문구를 정확히 입력해야 합니다.</div>
                <code>{api.cloudCopyApprovalPhrase(candidate, "copy-only")}</code>
''',
        '''            {#if copyEligible(candidate)}
              {@const copyOnlyApprovalPhrase = copyApprovalPhrase(candidate, "copy-only")}
              <div class="copy-approval">
                <div class="context">현재 메타데이터·출발지·목적지에 결부된 문구를 정확히 입력해야 합니다.</div>
                <code>{copyOnlyApprovalPhrase ?? "승인 문구를 불러오지 못했습니다."}</code>
''',
    )
    replace_once(
        ARCHIVE,
        '''                    || (copyConfirmations[candidate.metadata_fingerprint] ?? "").trim()
                      !== api.cloudCopyApprovalPhrase(candidate, "copy-only")}
''',
        '''                    || !copyOnlyApprovalPhrase
                    || (copyConfirmations[candidate.metadata_fingerprint] ?? "").trim()
                      !== copyOnlyApprovalPhrase}
''',
    )
    replace_once(
        ARCHIVE,
        '''            {#if adoptEligible(candidate)}
              <div class="copy-approval">
                <div class="context">기존 목적지 파일의 전체 해시 검증·채택도 정확한 별도 승인이 필요합니다.</div>
                <code>{api.cloudCopyApprovalPhrase(candidate, "adopt-existing-copy")}</code>
''',
        '''            {#if adoptEligible(candidate)}
              {@const adoptExistingApprovalPhrase = copyApprovalPhrase(candidate, "adopt-existing-copy")}
              <div class="copy-approval">
                <div class="context">기존 목적지 파일의 전체 해시 검증·채택도 정확한 별도 승인이 필요합니다.</div>
                <code>{adoptExistingApprovalPhrase ?? "승인 문구를 불러오지 못했습니다."}</code>
''',
    )
    replace_once(
        ARCHIVE,
        '''                    || (copyConfirmations[candidate.metadata_fingerprint] ?? "").trim()
                      !== api.cloudCopyApprovalPhrase(candidate, "adopt-existing-copy")}
''',
        '''                    || !adoptExistingApprovalPhrase
                    || (copyConfirmations[candidate.metadata_fingerprint] ?? "").trim()
                      !== adoptExistingApprovalPhrase}
''',
    )


def apply_api_tests() -> None:
    """Cover both action branches and the missing-current-plan failure path."""
    replace_once(
        API_TEST,
        '''describe("cloud copy approval phrase", () => {
  it("binds the exact review fingerprint and requested action", () => {
    const candidate = { review_fingerprint: "a".repeat(64) };
    expect(api.cloudCopyApprovalPhrase(candidate, "copy-only")).toBe(
      `DiskSage cloud copy-only ${"a".repeat(64)} 승인`,
    );
    expect(api.cloudCopyApprovalPhrase(candidate, "adopt-existing-copy")).toBe(
      `DiskSage cloud adopt-existing-copy ${"a".repeat(64)} 승인`,
    );
  });
});
''',
        '''describe("cloud copy approval phrase", () => {
  const reviewFingerprint = "a".repeat(64);
  const candidate = { review_fingerprint: reviewFingerprint };
  const phraseSets = {
    [reviewFingerprint]: {
      copy_only: "backend copy-only approval",
      adopt_existing_copy: "backend existing-copy adoption",
    },
  };

  it("selects each backend-returned action phrase for the exact review fingerprint", () => {
    expect(api.cloudCopyApprovalPhrase(candidate, "copy-only", phraseSets)).toBe(
      "backend copy-only approval",
    );
    expect(api.cloudCopyApprovalPhrase(candidate, "adopt-existing-copy", phraseSets)).toBe(
      "backend existing-copy adoption",
    );
  });

  it("fails closed when the current plan omitted the exact review fingerprint", () => {
    expect(api.cloudCopyApprovalPhrase(candidate, "copy-only", {})).toBeNull();
    expect(api.cloudCopyApprovalPhrase(candidate, "adopt-existing-copy", {})).toBeNull();
  });
});
''',
    )


def update_changelog() -> None:
    """Record the completed policy-ownership repair once in the unreleased notes."""
    text = CHANGELOG.read_text(encoding="utf-8")
    entry = (
        "- Source cloud copy and existing-copy adoption approval phrases from the Rust "
        "plan response, so the frontend cannot drift from the authorization policy.\n"
    )
    if entry in text:
        return
    marker = "## [Unreleased]\n"
    if text.count(marker) != 1:
        raise SystemExit("CHANGELOG missing one [Unreleased] section")
    CHANGELOG.write_text(text.replace(marker, marker + "\n" + entry, 1), encoding="utf-8")


def apply_repair() -> None:
    """Apply the production repair only after the regression has failed."""
    apply_commands_repair()
    apply_api_repair()
    apply_archive_repair()
    apply_api_tests()
    update_changelog()


def cleanup() -> None:
    """Remove the completed one-shot workflow and helper before publishing."""
    for path in (WORKFLOW, SCRIPT):
        if not path.exists():
            raise SystemExit(f"expected one-shot path to exist: {path}")
    WORKFLOW.unlink()
    SCRIPT.unlink()


def main() -> None:
    """Run one exact-head phase selected by the bounded workflow."""
    parser = argparse.ArgumentParser()
    parser.add_argument("phase", choices=("add-test", "apply", "cleanup"))
    args = parser.parse_args()
    if args.phase == "add-test":
        add_test()
    elif args.phase == "apply":
        apply_repair()
    else:
        cleanup()


if __name__ == "__main__":
    main()
