//! Backend-authored cloud-plan presentation contract.
//!
//! The core planner remains independent of approval presentation. This adapter enriches each
//! serialized candidate with the only action currently available and the exact phrase generated by
//! Rust for that action. Frontends may display the value but must not reconstruct authorization
//! text independently.

use crate::cloud::{
    CloudCandidate, CloudPlanOptions, CloudPlanReport, CloudRoot, ExactDuplicateSummary,
    PreCopyEvidenceCohort,
};
use crate::cloud_transfer::{
    cloud_copy_approval_phrase, CloudCopyApprovalAction, MAX_CLOUD_COPY_APPROVAL_AGE_MS,
};
use crate::provider_capacity::CloudCapacityAssessment;
use crate::volume_pressure::LocalVolumeSnapshot;
use std::path::Path;

const PLAN_WIDE_HEADROOM_BLOCKERS: [&str; 2] = [
    "local-volume-headroom-insufficient",
    "local-volume-headroom-unverified",
];
const PARTIAL_HEADROOM_NOTICE: &str = "local-volume-headroom-partial";

/// Keep the desktop plan's plan-wide headroom notices honest at candidate granularity.
///
/// The core planner records a stable aggregate notice whenever any candidate's destination probe
/// fails. The desktop historically treated those aggregate notices as blanket copy-button gates,
/// even though mutation-time native copy revalidates headroom for the selected candidate. If at
/// least one otherwise-unblocked candidate has verified destination/staging headroom, replace the
/// blanket blocker with a non-blocking partial diagnostic. Plans where no candidate can establish
/// headroom keep the original fail-closed blocker. This does not grant mutation authority: the
/// per-candidate copy boundary still performs the authoritative probe immediately before staging.
pub fn normalize_native_copy_headroom_notices(report: &mut CloudPlanReport) {
    if !report
        .notices
        .iter()
        .any(|notice| PLAN_WIDE_HEADROOM_BLOCKERS.contains(&notice.as_str()))
    {
        return;
    }

    let has_verified_candidate = report
        .candidates
        .iter()
        .filter(|candidate| candidate.blocked_reason.is_none())
        .any(|candidate| {
            crate::copy_headroom::require_destination_copy_headroom(
                Path::new(&candidate.dst),
                candidate.bytes,
                report.generated_at_ms,
            )
            .is_ok()
        });
    if !has_verified_candidate {
        return;
    }

    // An unsafe destination ancestor is a preview diagnostic, not a copy denial, but only when
    // another candidate has established destination headroom. Without that proof, retain the
    // candidate blocker so the serialized action cannot advertise an approval phrase for an
    // unverified staging path. The mutation boundary still re-probes the exact path immediately
    // before staging.
    for candidate in &mut report.candidates {
        if candidate
            .blocked_reason
            .as_deref()
            .is_some_and(|reason| reason.starts_with("local-volume-headroom-destination-"))
        {
            candidate.blocked_reason = None;
        }
    }

    report
        .notices
        .retain(|notice| !PLAN_WIDE_HEADROOM_BLOCKERS.contains(&notice.as_str()));
    if !report
        .notices
        .iter()
        .any(|notice| notice == PARTIAL_HEADROOM_NOTICE)
    {
        report.notices.push(PARTIAL_HEADROOM_NOTICE.into());
    }
}

/// One cloud candidate plus the backend-authored approval presentation for its current state.
#[derive(Debug, Clone, serde::Serialize)]
pub struct CloudPlanCandidateView {
    /// Original candidate evidence and destination decision fields.
    #[serde(flatten)]
    pub candidate: CloudCandidate,
    /// Exact action available for this candidate, or `None` when another blocker applies.
    pub copy_approval_action: Option<CloudCopyApprovalAction>,
    /// Candidate-specific confirmation phrase generated by Rust, or null when blocked.
    pub exact_copy_approval_phrase: Option<String>,
    /// Maximum age, in milliseconds, accepted for an approval created from this plan.
    pub copy_approval_max_age_ms: u64,
}

impl From<CloudCandidate> for CloudPlanCandidateView {
    fn from(candidate: CloudCandidate) -> Self {
        let action = match candidate.blocked_reason.as_deref() {
            None => Some(CloudCopyApprovalAction::CopyOnly),
            Some("destination-exists") => Some(CloudCopyApprovalAction::AdoptExistingCopy),
            Some(_) => None,
        };
        let exact_copy_approval_phrase =
            action.map(|action| cloud_copy_approval_phrase(&candidate, action));
        Self {
            candidate,
            copy_approval_action: action,
            exact_copy_approval_phrase,
            copy_approval_max_age_ms: MAX_CLOUD_COPY_APPROVAL_AGE_MS,
        }
    }
}

/// Serialized cloud plan consumed by the desktop UI and compatible CWL modules.
#[derive(Debug, Clone, serde::Serialize)]
pub struct CloudPlanReportView {
    /// Destination root selected and revalidated by the planner.
    pub cloud_root: CloudRoot,
    /// Millisecond Unix timestamp at which the plan was generated.
    pub generated_at_ms: u64,
    /// Source-selection policy used to collect this bounded candidate set.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source_selection_policy: Option<CloudPlanOptions>,
    /// Candidate evidence enriched with backend-authored approval presentation.
    pub candidates: Vec<CloudPlanCandidateView>,
    /// Total logical bytes represented by all candidates.
    pub candidate_bytes: u64,
    /// Candidate bytes that may become locally reclaimable after all safety gates pass.
    pub potentially_reclaimable_bytes: u64,
    /// Read-only exact-duplicate analysis attached to the plan.
    pub exact_duplicates: ExactDuplicateSummary,
    /// Authenticated provider capacity evidence when available.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub capacity: Option<CloudCapacityAssessment>,
    /// Native source-volume pressure observed while preparing this plan.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub local_volume: Option<LocalVolumeSnapshot>,
    /// Freshness/integrity cohort for the pre-copy evidence streams.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pre_copy_evidence: Option<PreCopyEvidenceCohort>,
    /// Stable operator notices produced by the planner and provider gates.
    pub notices: Vec<String>,
}

impl From<CloudPlanReport> for CloudPlanReportView {
    fn from(mut report: CloudPlanReport) -> Self {
        normalize_native_copy_headroom_notices(&mut report);
        let CloudPlanReport {
            cloud_root,
            generated_at_ms,
            source_selection_policy,
            candidates,
            candidate_bytes,
            potentially_reclaimable_bytes,
            exact_duplicates,
            capacity,
            local_volume,
            pre_copy_evidence,
            notices,
        } = report;
        Self {
            cloud_root,
            generated_at_ms,
            source_selection_policy,
            candidates: candidates
                .into_iter()
                .map(CloudPlanCandidateView::from)
                .collect(),
            candidate_bytes,
            potentially_reclaimable_bytes,
            exact_duplicates,
            capacity,
            local_volume,
            pre_copy_evidence,
            notices,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cloud::{ArchiveKind, CloudAccountScope, CloudProvider, MetadataEvidence};

    fn candidate(blocked_reason: Option<&str>) -> CloudCandidate {
        CloudCandidate {
            metadata_fingerprint: "a".repeat(64),
            review_fingerprint: "b".repeat(64),
            src: "/source/report.pdf".into(),
            dst: "/cloud/DiskSage Archive/documents/report.pdf".into(),
            provider: CloudProvider::Icloud,
            destination_account_scope: CloudAccountScope::Personal,
            kind: ArchiveKind::Document,
            bytes: 4096,
            age_days: 120,
            created_ms: 1,
            modified_ms: 2,
            production_time_ms: 1,
            production_time_source: "embedded:pdf".into(),
            production_time_confidence: "high".into(),
            source_root: "/source".into(),
            relative_path: "report.pdf".into(),
            source_context: "source".into(),
            requires_review: false,
            review_reasons: Vec::new(),
            content_title: Some("Report".into()),
            content_authors: vec!["Analyst".into()],
            content_context: Vec::new(),
            duration_ms: None,
            dataset_profile: None,
            metadata_evidence: vec![MetadataEvidence {
                field: "title".into(),
                value: "Report".into(),
                source: "pdf-info".into(),
                confidence: "high".into(),
            }],
            blocked_reason: blocked_reason.map(str::to_owned),
        }
    }

    #[test]
    fn new_copy_candidate_exports_rust_phrase_and_lifetime() {
        let view = CloudPlanCandidateView::from(candidate(None));
        assert_eq!(
            view.copy_approval_action,
            Some(CloudCopyApprovalAction::CopyOnly)
        );
        assert_eq!(
            view.exact_copy_approval_phrase.as_deref(),
            Some(format!("DiskSage cloud copy-only {} 승인", "b".repeat(64)).as_str())
        );
        assert_eq!(
            view.copy_approval_max_age_ms,
            MAX_CLOUD_COPY_APPROVAL_AGE_MS
        );
        let serialized = serde_json::to_value(&view).unwrap();
        assert_eq!(serialized["copy_approval_action"], "copy-only");
        assert_eq!(serialized["copy_approval_max_age_ms"], 900_000);
    }

    #[test]
    fn destination_collision_exports_existing_copy_adoption_phrase() {
        let view = CloudPlanCandidateView::from(candidate(Some("destination-exists")));
        assert_eq!(
            view.copy_approval_action,
            Some(CloudCopyApprovalAction::AdoptExistingCopy)
        );
        assert_eq!(
            view.exact_copy_approval_phrase.as_deref(),
            Some(format!("DiskSage cloud adopt-existing-copy {} 승인", "b".repeat(64)).as_str())
        );
    }

    #[test]
    fn unrelated_blocker_exports_no_authorization_text() {
        let view = CloudPlanCandidateView::from(candidate(Some("source-changed")));
        assert_eq!(view.copy_approval_action, None);
        assert_eq!(view.exact_copy_approval_phrase, None);
        let serialized = serde_json::to_value(&view).unwrap();
        assert!(serialized["copy_approval_action"].is_null());
        assert!(serialized["exact_copy_approval_phrase"].is_null());
    }

    #[test]
    fn normalization_keeps_unverified_destination_headroom_preview_block() {
        let mut report = CloudPlanReport {
            cloud_root: CloudRoot {
                id: "google-drive-personal".into(),
                provider: CloudProvider::GoogleDrive,
                account_scope: CloudAccountScope::Personal,
                label: "Google Drive".into(),
                path: "/cloud".into(),
                readable: true,
                access_issue: None,
            },
            generated_at_ms: 42,
            source_selection_policy: Some(CloudPlanOptions::default()),
            candidates: vec![candidate(Some(
                "local-volume-headroom-destination-parent-unsafe",
            ))],
            candidate_bytes: 4096,
            potentially_reclaimable_bytes: 0,
            exact_duplicates: ExactDuplicateSummary::default(),
            capacity: None,
            local_volume: None,
            pre_copy_evidence: None,
            notices: vec!["local-volume-headroom-unverified".into()],
        };
        report.candidates[0].bytes = u64::MAX;
        report.candidate_bytes = u64::MAX;

        normalize_native_copy_headroom_notices(&mut report);

        assert_eq!(
            report.candidates[0].blocked_reason.as_deref(),
            Some("local-volume-headroom-destination-parent-unsafe")
        );
        assert!(report
            .notices
            .contains(&"local-volume-headroom-unverified".to_string()));
    }

    #[test]
    fn report_conversion_preserves_plan_evidence_and_enriches_candidates() {
        let report = CloudPlanReport {
            cloud_root: CloudRoot {
                id: "icloud-personal".into(),
                provider: CloudProvider::Icloud,
                account_scope: CloudAccountScope::Personal,
                label: "iCloud Drive".into(),
                path: "/cloud".into(),
                readable: true,
                access_issue: None,
            },
            generated_at_ms: 42,
            source_selection_policy: Some(CloudPlanOptions::default()),
            candidates: vec![candidate(None)],
            candidate_bytes: 4096,
            potentially_reclaimable_bytes: 4096,
            exact_duplicates: ExactDuplicateSummary::default(),
            capacity: None,
            local_volume: None,
            pre_copy_evidence: None,
            notices: vec!["cloud-quota-provider-native-verified".into()],
        };
        let view = CloudPlanReportView::from(report);
        assert_eq!(view.generated_at_ms, 42);
        assert_eq!(view.candidate_bytes, 4096);
        assert_eq!(view.candidates.len(), 1);
        assert_eq!(
            view.candidates[0].copy_approval_action,
            Some(CloudCopyApprovalAction::CopyOnly)
        );
        assert_eq!(
            view.notices,
            vec!["cloud-quota-provider-native-verified".to_string()]
        );
    }
}
